### ISSUE TITLE
Training settings?

### ISSUE THREAD

**Issue by NimSed** [sniklaus/pytorch-pwc#11]
Thanks for sharing this nice piece of code.
Was wondering if you are planning to share the training settings / scripts?

Also in a related question, what do you think was the source of discrepancy in the two original implementations (caffe vs. pytorch) and how do you think it got solved?

Best,

**Comment by sniklaus** [comment]
I am afraid that I have not trained it myself and instead simply converted the official Caffe weights. This is also why there is no difference between the official Caffe version and this reimplementation.

**Comment by NimSed** [comment]
Hi. Thanks for your reply.
Apparently in the original pytorch version the authors have done the same thing (convert, not train):
https://github.com/NVlabs/PWC-Net/issues/43#issuecomment-427990562
So, still it can be interesting to know what the difference is.

**Comment by sniklaus** [comment]
You are correct. Zhile Ren, who created the official PyTorch version, got in touch with me after I created this repository and they subsequently also switched to converting the Caffe weights instead of training the PyTorch version separately. To the best of my knowledge, the two versions should produce equivalent results now. However, this reimplementation seems to work more gracefully with recent versions of PyTorch and / or Python.
