### ISSUE TITLE
Do you have a model trained on Kitti dataset?

### ISSUE THREAD

**Issue by ZheC** [sniklaus/pytorch-pwc#9]
Thank you for the re-implementation! It is so helpful. Do you have a model trained on the Kitti flow 2015 dataset?

**Comment by sniklaus** [comment]
I am afraid that an official model trained on KITTI has not been released yet [1]. Since I am trying to stick as close as possible to the original repository, and also did not train on KITTI myself, I have not planned to release such a model. My apologies, but thank you for being interested in this implementation.

[1] https://github.com/NVlabs/PWC-Net/tree/master/Caffe/model

**Comment by ZheC** [comment]
I think the pwc_net.pth.tar in the original repo is finetuned on kitti dataset as well [1]. Which model in your repo corresponds to pwc_net.pth.tar?

[1] https://github.com/NVlabs/PWC-Net/issues/26

**Comment by sniklaus** [comment]
`--model sintel` corresponds to `pwc_net.caffemodel`
`--model chairs-things` corresponds do `pwc_net_chairs_things.caffemodel`

I should probably change `--model sintel` to `--model various` since Deqing mentioned that it has been fine-tuned on a diverse set of training data: https://github.com/NVlabs/PWC-Net/issues/26#issuecomment-413752445

Thank you for bringing this to my attention.

**Comment by sniklaus** [comment]
I just changed `--model sintel` to `--model default`. Thank you again for bringing this up.

**Comment by SteveSZF** [comment]
Is the KITTI model only fine-tuned on KITTI2015? not a mixture of KITTI2012 and 2015?

**Comment by sniklaus** [comment]
According to https://github.com/NVlabs/PWC-Net/issues/26#issuecomment-413752445, yes. You might want to consider asking your question there to get a definitive answer.
